# Generated by Django 6.0.3 on 2026-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reference",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
