# Generated by Django 6.0.3 on 2026-03-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('WALNUT', 'Walnut'), ('CHERRY', 'Cherry'), ('OAK', 'Oak'), ('MAPLE', 'Maple'), ('ASH', 'Ash'), ('YEW', 'Yew'), ('POPLAR', 'Poplar'), ('BIRCH', 'Birch')])),
                ('diameter', models.IntegerField(verbose_name='Diameter (cm)')),
                ('length', models.IntegerField(verbose_name='Length (cm)')),
                ('grade', models.CharField(choices=[('VENEER', 'Veneer'), ('FURNITURE', 'Furniture'), ('CABINETRY', 'Cabinetry'), ('CONSTRUCTION', 'Construction'), ('FIREWOOD', 'Firewood')])),
            ],
        ),
    ]
